name: Flutter Unit Tests

defaults:
  run:
    working-directory: packages/tide_kit

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'packages/tide_kit/CHANGELOG.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'packages/tide_kit/CHANGELOG.md'

jobs:
  test:
    strategy:
      matrix:
        flutter-version: ['3.24.0', '3.24.5', '3.27.4', '3.29.3', '3.32.2']
        os: [ubuntu-latest, macos-15, windows-latest]
    runs-on: ${{ matrix.os }}
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter ${{ matrix.flutter-version }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '${{ matrix.flutter-version }}'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Install example2 dependencies
        run: cd example2; flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run unit and widget tests
        run: flutter test --coverage --coverage-path=lcov.info
